#!/bin/bash

set -euo pipefail

echo "👉 Installer from github!"
echo "-------------------------------------------------"
echo

echo "🚀 Installing brew!"
echo "-------------------------------------------------"
sudo ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" </dev/null
echo "-------------------------------------------------"
echo

echo "🚀 Cloning dotfiles"
echo "-------------------------------------------------"
git clone --depth 1 https://github.com/apascualco/dotfiles.git "$HOME/.dotfiles"
echo

echo "🚀 Launch install.sh"
echo "-------------------------------------------------"
sh $HOME/.dotfiles/install.sh
echo
