if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Optional private configuration
source .local_zshrc
source .local_zshrc_alternative

export GOPATH="$HOME/go"
export PATH="$GOPATH/bin:$PATH"
export ZSH="$HOME/.oh-my-zsh"
export ARCHFLAGS="-arch x86_64"

ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(
  git 
  docker 
  docker-compose
  python 
  brew 
  git-flow 
  zsh-syntax-highlighting
  zsh-autosuggestions 
  fzf 
  golang
)

source $ZSH/oh-my-zsh.sh
export LANG=en_US.UTF-8
PS1='%n@%m %. %% '

# Alias 
alias di='docker images'
alias dca='docker ps -a'
alias dri='docker rmi --force $(docker images -a -q)'
alias drc='docker rm $(docker ps -a -q)'

alias lsource='source ~/.zshrc'
alias esource='vim ~/.zshrc'

#Kubernetes
alias kapp='kubectl apply -f '
alias kdapp='kubectl delete -f '

#Python
alias pte='./.venv/bin/pytest '
alias pdist='.venv/bin/python setup.py sdist'
alias venvc='virtualenv .venv --python='
alias venv2='virtualenv .venv --python=python2'
alias venv3='virtualenv .venv --python=python3'
alias venva='source .venv/bin/activate'
alias venvd='deactivate'

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
HIST_STAMPS="yyyy-mm-dd"

alias ctags="`brew --prefix`/bin/ctags"

# vim/nvim
alias n='nvim .'

# worksdir
alias wdgo='cd ~/workdir/code/go'
alias wdrust='cd ~/workdir/code/rust'
alias wdinfra='cd ~/workdir/code/infra'

# Gradle
alias gbc='./gradlew build --continuous --info'
alias gbc.='../gradlew build --continuous --info'
alias gbc..='../../gradlew build --continuous --info'
