source "$HOME/.cargo/env"
source "$HOME/.sdkman/bin/sdkman-init.sh"
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

eval "$(/opt/homebrew/bin/brew shellenv)"
GNUBINS="$(find `brew --prefix`/opt -type d -follow -name gnubin -print)"

for bindir in ${GNUBINS[@]}
do
  export PATH=$bindir:$PATH
done

export PATH="$HOME/.gvm/pkgsets/go1.20/global/src/k8s.io/kubernetes/third_party/etcd:${PATH}"
export PATH="/usr/local/bin:${PATH}"

export PATH="$HOME/workdir/tools/apache-maven-3.9.6/bin":${PATH}

# Optional private configuration
source ~/.local_zshrc
source ~/.local_zshrc_alternative


export PATH="$GOPATH/bin:$PATH"
export ZSH="$HOME/.oh-my-zsh"
export ARCHFLAGS="-arch x86_64"

export PATH="$HOME/.gvm/pkgsets/go1.20/global/bin:${PATH}"

ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(
  git 
  docker 
  docker-compose
  python 
  brew 
  git-flow 
  zsh-syntax-highlighting
  zsh-autosuggestions 
  fzf 
  golang
)

source $ZSH/oh-my-zsh.sh
export LANG=en_US.UTF-8
PS1='%n@%m %. %% '

# Alias 
alias di='docker images'
alias dca='docker ps -a'
alias dri='docker rmi --force $(docker images -a -q)'
alias drc='docker rm $(docker ps -a -q)'

alias lsource='source ~/.zshrc'
alias esource='vim ~/.zshrc'

#Kubernetes
alias kapp='kubectl apply -f '
alias kdapp='kubectl delete -f '

#Python
alias pte='./.venv/bin/pytest '
alias pdist='.venv/bin/python setup.py sdist'
alias venvc='virtualenv .venv --python='
alias venv2='virtualenv .venv --python=python2'
alias venv3='virtualenv .venv --python=python3'
alias venva='source .venv/bin/activate'
alias venvd='deactivate'

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
HIST_STAMPS="yyyy-mm-dd"

alias ctags="`brew --prefix`/bin/ctags"

# vim/nvim
alias n='nvim .'

# worksdir
alias wdgo='cd ~/workdir/code/go'
alias wdrust='cd ~/workdir/code/rust'
alias wdinfra='cd ~/workdir/code/infra'

# Gradle
alias gbc='./gradlew build --continuous --info'
alias gbc.='../gradlew build --continuous --info'
alias gbc..='../../gradlew build --continuous --info'
alias idea='open -na "IntelliJ IDEA.app" --args '
alias cab='git branch --merged | grep -v "\*" | xargs -n 1 git branch -d'

alias fckcache='sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder'
#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

[[ -s "$HOME/.gvm/scripts/gvm" ]] && source "$HOME/.gvm/scripts/gvm"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/apascualco/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/apascualco/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/apascualco/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/apascualco/Downloads/google-cloud-sdk/completion.zsh.inc'; fi
export GOPATH="$HOME/.gvm/pkgsets/go1.20/global"
export PATH="/opt/homebrew/bin/bash:${PATH}"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
[[ $commands[kubectl] ]] && source <(kubectl completion zsh)
