require("nvim-treesitter.configs").setup({
	modules = {},
	sync_install = false,
	auto_install = true,
	ignore_install = {},
	highlight = {
		enable = true,
		custom_captures = {},
		additional_vim_regex_highlighting = false,
	},
	incremental_selection = {
		enable = true,
		keymaps = {
			init_selection = "<C-space>",
			node_incremental = "<C-space>",
			scope_incremental = false,
			node_decremental = "<bs>",
		},
	},
	ensure_installed = {
		"bash",
		"c",
		"cmake",
		"css",
		"cpp",
		"diff",
		"dockerfile",
		"gitignore",
		"git_rebase",
		"go",
		"gomod",
		"gowork",
		"gosum",
		"gotmpl",
		"html",
		"java",
		"json",
		"json5",
		"kotlin",
		"lua",
		"make",
		"markdown",
		"python",
		"regex",
		"ruby",
		"rust",
		"scala",
		"scss",
		"slint",
		"tsx",
		"toml",
		"sql",
		"vim",
		"yaml",
		"terraform",
		"javascript",
		"typescript",
		"comment",
		"dap_repl"
	}
})